### ISSUE TITLE
Godel/godelinit install breaks under go1.17

### ISSUE THREAD

**Issue by dreamlibrarian** [palantir/godel#613] opened 2021-11-26 21:28 UTC
## What happened?

Starting from go1.17, attempted to install godelinit for a new project; failed with:

```
# github.com/palantir/godel/framework/builtintasks/installupdate
go/pkg/mod/github.com/palantir/godel@v2.20.0+incompatible/framework/builtintasks/installupdate/install.go:68:26: invalid method expression archiver.TarGz.Open (needs pointer receiver: (*archiver.TarGz).Open)
```

## What did you want to happen?

Should ideally be able to build/install godelinit from current golang version; alternately, godelinit in the release package would make this less troubling.

## Detailed output

```
$ go install github.com/palantir/godel/godelinit@latest
go: finding module for package gopkg.in/cheggaaa/pb.v1
go: finding module for package github.com/nmiyake/pkg/dirs
go: finding module for package github.com/mholt/archiver
go: finding module for package github.com/palantir/pkg/cobracli
go: finding module for package github.com/spf13/cobra
go: finding module for package github.com/palantir/pkg/specdir
go: finding module for package github.com/google/go-github/github
go: finding module for package github.com/pkg/errors
go: found github.com/palantir/pkg/cobracli in github.com/palantir/pkg/cobracli v1.0.1
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
go: found github.com/spf13/cobra in github.com/spf13/cobra v1.2.1
go: found github.com/google/go-github/github in github.com/google/go-github v17.0.0+incompatible
go: found github.com/mholt/archiver in github.com/mholt/archiver v3.1.1+incompatible
go: found github.com/nmiyake/pkg/dirs in github.com/nmiyake/pkg/dirs v1.1.0
go: found github.com/palantir/pkg/specdir in github.com/palantir/pkg/specdir v1.0.1
go: found gopkg.in/cheggaaa/pb.v1 in gopkg.in/cheggaaa/pb.v1 v1.0.28
go: finding module for package github.com/mattn/go-runewidth
go: finding module for package github.com/golang/snappy
go: finding module for package github.com/ulikunitz/xz
go: finding module for package github.com/pierrec/lz4
go: finding module for package github.com/dsnet/compress/bzip2
go: finding module for package github.com/nwaples/rardecode
go: finding module for package github.com/xi2/xz
go: finding module for package github.com/google/go-querystring/query
go: found github.com/google/go-querystring/query in github.com/google/go-querystring v1.1.0
go: found github.com/dsnet/compress/bzip2 in github.com/dsnet/compress v0.0.1
go: found github.com/golang/snappy in github.com/golang/snappy v0.0.4
go: found github.com/nwaples/rardecode in github.com/nwaples/rardecode v1.1.2
go: found github.com/pierrec/lz4 in github.com/pierrec/lz4 v2.6.1+incompatible
go: found github.com/ulikunitz/xz in github.com/ulikunitz/xz v0.5.10
go: found github.com/xi2/xz in github.com/xi2/xz v0.0.0-20171230120015-48954b6210f8
go: found github.com/mattn/go-runewidth in github.com/mattn/go-runewidth v0.0.13
# github.com/palantir/godel/framework/builtintasks/installupdate
go/pkg/mod/github.com/palantir/godel@v2.20.0+incompatible/framework/builtintasks/installupdate/install.go:68:26: invalid method expression archiver.TarGz.Open (needs pointer receiver: (*archiver.TarGz).Open)
$ go version
go version go1.17.3 linux/amd64
```

**Comment by dreamlibrarian** [comment] 2021-11-26 21:43
I haven't done any investigation as to why godelw builds godel and godelinit, and go install won't, but went ahead and added a trivial builder in dist-plugin.yml to build godelinit and it worked. Not sure if there's a cleverer answer.

**Comment by nmiyake** [comment] 2021-12-07 17:32
@dreamlibrarian the issue is that the install path you used doesn't include the `v2` that is necessary to fetch the latest version (because this module is at version 2.x). Per the documentation at https://github.com/palantir/godel/tree/master/godelinit, the `godelinit` installation command should be `go install github.com/palantir/godel/v2/godelinit@latest`.

Closing since I believe the above should resolve the issue, but if not feel free to chime in on the issue with more details if not and will be happy to follow up.

**Closed by nmiyake** 2021-12-07 17:32 UTC
